### ISSUE TITLE
websocket未处理data为error等问题

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_websocket#10]
ai给的修复，供参考
```python
# ... existing imports ...
from aiohttp import ClientSession, ClientWebSocketResponse, ServerTimeoutError, ClientConnectorError

class WebsocketClient:
    # ... existing code ...

    async def _run(self):
        """
        在事件循环中运行的主协程
        """
        self._session = ClientSession()

        while self._active:
            # 捕捉运行过程中异常
            try:
                # 发起Websocket连接
                self._ws = await self._session.ws_connect(
                    self._host,
                    proxy=self._proxy,
                    ssl=False,  # Disable SSL verification
                    heartbeat=self._ping_interval,
                    receive_timeout=self._receive_timeout
                )

                # 调用连接成功回调
                self.on_connected()

                # 持续处理收到的数据
                async for msg in self._ws:
                    if msg.type == aiohttp.WSMsgType.TEXT:
                        text: str = msg.data
                        self._record_last_received_text(text)

                        data: dict = self.unpack_data(text)
                        self.on_packet(data)
                    elif msg.type == aiohttp.WSMsgType.ERROR:
                        self.on_error(msg.type, msg.data, None)
                        break

                # 移除Websocket连接对象
                self._ws = None

                # 调用连接断开回调
                self.on_disconnected(0, "Websocket connection closed")
            except ServerTimeoutError as e:
                self.on_error(type(e), e, None)
                self.on_disconnected(0, "Websocket connection timeout")
            except ClientConnectorError as e:
                self.on_error(type(e), e, None)
                self.on_disconnected(0, f"Connection error: {str(e)}")
            except Exception as e:
                et, ev, tb = sys.exc_info()
                self.on_error(et, ev, tb)

            # Add a delay before reconnecting
            await asyncio.sleep(5)

    def _record_last_received_text(self, text: str):
        """记录最近收到的数据字符串"""
        if isinstance(text, str):
            self._last_received_text = text[:1000]
        else:
            self._last_received_text = str(text)[:1000]

    # ... rest of the code ...
```

报错代码：
```
WebsocketClient on error----------
[2024-10-24T16:19:21.269302]: Unhandled WebSocket Error:<class 'TypeError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 207, in _run
    self._record_last_received_text(text)
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 241, in _record_last_received_text
    self._last_received_text = text[:1000]
                               ~~~~^^^^^^^
TypeError: 'ServerTimeoutError' object is not subscriptable

WebsocketClient on error----------
[2024-10-24T16:19:24.259236]: Unhandled WebSocket Error:<class 'TypeError'>
LastSentText:
{"method": "SUBSCRIBE", "params": ["c98usdt@ticker", "c98usdt@depth5", "c98usdt@kline_1m"], "id": 1}
LastReceivedText:
{"stream":"c98usdt@depth5","data":{"e":"depthUpdate","E":1729757947937,"T":1729757947821,"s":"C98USDT","U":5590919143805,"u":5590919154301,"pu":5590918973037,"b":[["0.1270","23254"],["0.1269","117720"],["0.1268","340594"],["0.1267","262770"],["0.1266","168608"]],"a":[["0.1271","30113"],["0.1272","62022"],["0.1273","134668"],["0.1274","216143"],["0.1275","262057"]]}}
Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 207, in _run
    self._record_last_received_text(text)
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 241, in _record_last_received_text
    self._last_received_text = text[:1000]
                               ~~~~^^^^^^^
TypeError: 'ServerTimeoutError' object is not subscriptable

WebsocketClient on error----------
[2024-10-24T16:19:24.351981]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:27.440863]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:30.545859]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:33.791594]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:
{"method": "SUBSCRIBE", "params": ["c98usdt@ticker", "c98usdt@depth5", "c98usdt@kline_1m"], "id": 1}
LastReceivedText:
{"stream":"c98usdt@depth5","data":{"e":"depthUpdate","E":1729757947937,"T":1729757947821,"s":"C98USDT","U":5590919143805,"u":5590919154301,"pu":5590918973037,"b":[["0.1270","23254"],["0.1269","117720"],["0.1268","340594"],["0.1267","262770"],["0.1266","168608"]],"a":[["0.1271","30113"],["0.1272","62022"],["0.1273","134668"],["0.1274","216143"],["0.1275","262057"]]}}
Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:35.138608]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:36.891299]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:
{"method": "SUBSCRIBE", "params": ["c98usdt@ticker", "c98usdt@depth5", "c98usdt@kline_1m"], "id": 1}
LastReceivedText:
{"stream":"c98usdt@depth5","data":{"e":"depthUpdate","E":1729757947937,"T":1729757947821,"s":"C98USDT","U":5590919143805,"u":5590919154301,"pu":5590918973037,"b":[["0.1270","23254"],["0.1269","117720"],["0.1268","340594"],["0.1267","262770"],["0.1266","168608"]],"a":[["0.1271","30113"],["0.1272","62022"],["0.1273","134668"],["0.1274","216143"],["0.1275","262057"]]}}
Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:38.228750]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:41.334364]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:42.875094]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:
{"method": "SUBSCRIBE", "params": ["c98usdt@ticker", "c98usdt@depth5", "c98usdt@kline_1m"], "id": 1}
LastReceivedText:
{"stream":"c98usdt@depth5","data":{"e":"depthUpdate","E":1729757947937,"T":1729757947821,"s":"C98USDT","U":5590919143805,"u":5590919154301,"pu":5590918973037,"b":[["0.1270","23254"],["0.1269","117720"],["0.1268","340594"],["0.1267","262770"],["0.1266","168608"]],"a":[["0.1271","30113"],["0.1272","62022"],["0.1273","134668"],["0.1274","216143"],["0.1275","262057"]]}}
Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

WebsocketClient on error----------
[2024-10-24T16:19:45.957188]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:
{"method": "SUBSCRIBE", "params": ["c98usdt@ticker", "c98usdt@depth5", "c98usdt@kline_1m"], "id": 1}
LastReceivedText:
{"stream":"c98usdt@depth5","data":{"e":"depthUpdate","E":1729757947937,"T":1729757947821,"s":"C98USDT","U":5590919143805,"u":5590919154301,"pu":5590918973037,"b":[["0.1270","23254"],["0.1269","117720"],["0.1268","340594"],["0.1267","262770"],["0.1266","168608"]],"a":[["0.1271","30113"],["0.1272","62022"],["0.1273","134668"],["0.1274","216143"],["0.1275","262057"]]}}
Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]

2024-10-24 16:19:46.367 | Level 20 | vnpy_evo.trader.engine:process_log_event:75 - Data Websocket API is connected
WebsocketClient on error----------
[2024-10-24T16:19:47.341646]: Unhandled WebSocket Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
LastSentText:

LastReceivedText:

Exception trace: 
Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1214, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\asyncio\base_events.py", line 1303, in start_tls
    await waiter
  File "S:\Envs\evo\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Envs\evo\Lib\site-packages\vnpy_websocket\websocket_client.py", line 193, in _run
    self._ws = await self._session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 931, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1472, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Envs\evo\Lib\site-packages\aiohttp\connector.py", line 1234, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host fstream.binance.com:443 ssl:False [None]
```

**Comment by vnpy** [comment]
感谢反馈，目前版本已经改回线程池模式，建议使用新版本试下
